
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file EdAcadYearFaculty.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using UMIS_VER2.BusinessLyer.Validation;
#endregion

namespace UMIS_VER2.BusinessLyer
{
	///<summary>
	/// An object representation of the 'ED_ACAD_YEAR_FACULTY' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class EdAcadYearFacultyBase : EntityBase, IEdAcadYearFaculty, IEntityId<EdAcadYearFacultyKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private EdAcadYearFacultyEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private EdAcadYearFacultyEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private EdAcadYearFacultyEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<EdAcadYearFaculty> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event EdAcadYearFacultyEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event EdAcadYearFacultyEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="EdAcadYearFacultyBase"/> instance.
		///</summary>
		public EdAcadYearFacultyBase()
		{
			this.entityData = new EdAcadYearFacultyEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="EdAcadYearFacultyBase"/> instance.
		///</summary>
		///<param name="_edAcadYearFacultyId">XXX</param>
		///<param name="_asFacultyInfoId"></param>
		///<param name="_edAcadYearId"></param>
		///<param name="_startDate"></param>
		///<param name="_endDate"></param>
		///<param name="_currentYear"></param>
		///<param name="_isClosed"></param>
		///<param name="_asCodeDegreeClassId"></param>
		public EdAcadYearFacultyBase(System.Decimal _edAcadYearFacultyId, System.Decimal? _asFacultyInfoId, 
			System.Decimal _edAcadYearId, System.DateTime _startDate, System.DateTime _endDate, 
			System.Decimal? _currentYear, System.Decimal? _isClosed, System.Decimal? _asCodeDegreeClassId)
		{
			this.entityData = new EdAcadYearFacultyEntityData();
			this.backupData = null;

			this.EdAcadYearFacultyId = _edAcadYearFacultyId;
			this.AsFacultyInfoId = _asFacultyInfoId;
			this.EdAcadYearId = _edAcadYearId;
			this.StartDate = _startDate;
			this.EndDate = _endDate;
			this.CurrentYear = _currentYear;
			this.IsClosed = _isClosed;
			this.AsCodeDegreeClassId = _asCodeDegreeClassId;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="EdAcadYearFaculty"/> instance.
		///</summary>
		///<param name="_edAcadYearFacultyId">XXX</param>
		///<param name="_asFacultyInfoId"></param>
		///<param name="_edAcadYearId"></param>
		///<param name="_startDate"></param>
		///<param name="_endDate"></param>
		///<param name="_currentYear"></param>
		///<param name="_isClosed"></param>
		///<param name="_asCodeDegreeClassId"></param>
		public static EdAcadYearFaculty CreateEdAcadYearFaculty(System.Decimal _edAcadYearFacultyId, System.Decimal? _asFacultyInfoId, 
			System.Decimal _edAcadYearId, System.DateTime _startDate, System.DateTime _endDate, 
			System.Decimal? _currentYear, System.Decimal? _isClosed, System.Decimal? _asCodeDegreeClassId)
		{
			EdAcadYearFaculty newEdAcadYearFaculty = new EdAcadYearFaculty();
			newEdAcadYearFaculty.EdAcadYearFacultyId = _edAcadYearFacultyId;
			newEdAcadYearFaculty.AsFacultyInfoId = _asFacultyInfoId;
			newEdAcadYearFaculty.EdAcadYearId = _edAcadYearId;
			newEdAcadYearFaculty.StartDate = _startDate;
			newEdAcadYearFaculty.EndDate = _endDate;
			newEdAcadYearFaculty.CurrentYear = _currentYear;
			newEdAcadYearFaculty.IsClosed = _isClosed;
			newEdAcadYearFaculty.AsCodeDegreeClassId = _asCodeDegreeClassId;
			return newEdAcadYearFaculty;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the EdAcadYearFacultyId property. 
		///		XXX
		/// </summary>
		/// <value>This type is numeric.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@"XXX"), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Decimal EdAcadYearFacultyId
		{
			get
			{
				return this.entityData.EdAcadYearFacultyId; 
			}
			
			set
			{
				if (this.entityData.EdAcadYearFacultyId == value)
					return;
					
				OnColumnChanging(EdAcadYearFacultyColumn.EdAcadYearFacultyId, this.entityData.EdAcadYearFacultyId);
				this.entityData.EdAcadYearFacultyId = value;
				this.EntityId.EdAcadYearFacultyId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EdAcadYearFacultyColumn.EdAcadYearFacultyId, this.entityData.EdAcadYearFacultyId);
				OnPropertyChanged("EdAcadYearFacultyId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the ED_ACAD_YEAR_FACULTY_ID property.
		///		XXX
		/// </summary>
		/// <remarks>This is the original value of the ED_ACAD_YEAR_FACULTY_ID property.</remarks>
		/// <value>This type is numeric</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Decimal OriginalEdAcadYearFacultyId
		{
			get { return this.entityData.OriginalEdAcadYearFacultyId; }
			set { this.entityData.OriginalEdAcadYearFacultyId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the AsFacultyInfoId property. 
		///		
		/// </summary>
		/// <value>This type is numeric.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsAsFacultyInfoIdNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Decimal? AsFacultyInfoId
		{
			get
			{
				return this.entityData.AsFacultyInfoId; 
			}
			
			set
			{
				if (this.entityData.AsFacultyInfoId == value)
					return;
					
				OnColumnChanging(EdAcadYearFacultyColumn.AsFacultyInfoId, this.entityData.AsFacultyInfoId);
				this.entityData.AsFacultyInfoId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EdAcadYearFacultyColumn.AsFacultyInfoId, this.entityData.AsFacultyInfoId);
				OnPropertyChanged("AsFacultyInfoId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the EdAcadYearId property. 
		///		
		/// </summary>
		/// <value>This type is numeric.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Decimal EdAcadYearId
		{
			get
			{
				return this.entityData.EdAcadYearId; 
			}
			
			set
			{
				if (this.entityData.EdAcadYearId == value)
					return;
					
				OnColumnChanging(EdAcadYearFacultyColumn.EdAcadYearId, this.entityData.EdAcadYearId);
				this.entityData.EdAcadYearId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EdAcadYearFacultyColumn.EdAcadYearId, this.entityData.EdAcadYearId);
				OnPropertyChanged("EdAcadYearId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the StartDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime StartDate
		{
			get
			{
				return this.entityData.StartDate; 
			}
			
			set
			{
				if (this.entityData.StartDate == value)
					return;
					
				OnColumnChanging(EdAcadYearFacultyColumn.StartDate, this.entityData.StartDate);
				this.entityData.StartDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EdAcadYearFacultyColumn.StartDate, this.entityData.StartDate);
				OnPropertyChanged("StartDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the EndDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime EndDate
		{
			get
			{
				return this.entityData.EndDate; 
			}
			
			set
			{
				if (this.entityData.EndDate == value)
					return;
					
				OnColumnChanging(EdAcadYearFacultyColumn.EndDate, this.entityData.EndDate);
				this.entityData.EndDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EdAcadYearFacultyColumn.EndDate, this.entityData.EndDate);
				OnPropertyChanged("EndDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CurrentYear property. 
		///		
		/// </summary>
		/// <value>This type is numeric.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsCurrentYearNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Decimal? CurrentYear
		{
			get
			{
				return this.entityData.CurrentYear; 
			}
			
			set
			{
				if (this.entityData.CurrentYear == value)
					return;
					
				OnColumnChanging(EdAcadYearFacultyColumn.CurrentYear, this.entityData.CurrentYear);
				this.entityData.CurrentYear = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EdAcadYearFacultyColumn.CurrentYear, this.entityData.CurrentYear);
				OnPropertyChanged("CurrentYear");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IsClosed property. 
		///		
		/// </summary>
		/// <value>This type is numeric.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsIsClosedNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Decimal? IsClosed
		{
			get
			{
				return this.entityData.IsClosed; 
			}
			
			set
			{
				if (this.entityData.IsClosed == value)
					return;
					
				OnColumnChanging(EdAcadYearFacultyColumn.IsClosed, this.entityData.IsClosed);
				this.entityData.IsClosed = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EdAcadYearFacultyColumn.IsClosed, this.entityData.IsClosed);
				OnPropertyChanged("IsClosed");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the AsCodeDegreeClassId property. 
		///		
		/// </summary>
		/// <value>This type is numeric.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsAsCodeDegreeClassIdNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Decimal? AsCodeDegreeClassId
		{
			get
			{
				return this.entityData.AsCodeDegreeClassId; 
			}
			
			set
			{
				if (this.entityData.AsCodeDegreeClassId == value)
					return;
					
				OnColumnChanging(EdAcadYearFacultyColumn.AsCodeDegreeClassId, this.entityData.AsCodeDegreeClassId);
				this.entityData.AsCodeDegreeClassId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EdAcadYearFacultyColumn.AsCodeDegreeClassId, this.entityData.AsCodeDegreeClassId);
				OnPropertyChanged("AsCodeDegreeClassId");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="EdAcadYear"/>.
		/// </summary>
		/// <value>The source EdAcadYear for EdAcadYearId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual EdAcadYear EdAcadYearIdSource
      	{
            get { return entityData.EdAcadYearIdSource; }
            set { entityData.EdAcadYearIdSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="AsCodeDegreeClass"/>.
		/// </summary>
		/// <value>The source AsCodeDegreeClass for AsCodeDegreeClassId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual AsCodeDegreeClass AsCodeDegreeClassIdSource
      	{
            get { return entityData.AsCodeDegreeClassIdSource; }
            set { entityData.AsCodeDegreeClassIdSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="AsFacultyInfo"/>.
		/// </summary>
		/// <value>The source AsFacultyInfo for AsFacultyInfoId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual AsFacultyInfo AsFacultyInfoIdSource
      	{
            get { return entityData.AsFacultyInfoIdSource; }
            set { entityData.AsFacultyInfoIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "ED_ACAD_YEAR_FACULTY"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ED_ACAD_YEAR_FACULTY_ID", "AS_FACULTY_INFO_ID", "ED_ACAD_YEAR_ID", "START_DATE", "END_DATE", "CURRENT_YEAR", "IS_CLOSED", "AS_CODE_DEGREE_CLASS_ID"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as EdAcadYearFacultyEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (EdAcadYearFaculty) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<EdAcadYearFaculty>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as EdAcadYearFaculty);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed EdAcadYearFaculty Entity 
		///</summary>
		protected virtual EdAcadYearFaculty Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			EdAcadYearFaculty copy = new EdAcadYearFaculty();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.EdAcadYearFacultyId = this.EdAcadYearFacultyId;
					copy.OriginalEdAcadYearFacultyId = this.OriginalEdAcadYearFacultyId;
				copy.AsFacultyInfoId = this.AsFacultyInfoId;
				copy.EdAcadYearId = this.EdAcadYearId;
				copy.StartDate = this.StartDate;
				copy.EndDate = this.EndDate;
				copy.CurrentYear = this.CurrentYear;
				copy.IsClosed = this.IsClosed;
				copy.AsCodeDegreeClassId = this.AsCodeDegreeClassId;
			
			if (this.EdAcadYearIdSource != null && existingCopies.Contains(this.EdAcadYearIdSource))
				copy.EdAcadYearIdSource = existingCopies[this.EdAcadYearIdSource] as EdAcadYear;
			else
				copy.EdAcadYearIdSource = MakeCopyOf(this.EdAcadYearIdSource, existingCopies) as EdAcadYear;
			if (this.AsCodeDegreeClassIdSource != null && existingCopies.Contains(this.AsCodeDegreeClassIdSource))
				copy.AsCodeDegreeClassIdSource = existingCopies[this.AsCodeDegreeClassIdSource] as AsCodeDegreeClass;
			else
				copy.AsCodeDegreeClassIdSource = MakeCopyOf(this.AsCodeDegreeClassIdSource, existingCopies) as AsCodeDegreeClass;
			if (this.AsFacultyInfoIdSource != null && existingCopies.Contains(this.AsFacultyInfoIdSource))
				copy.AsFacultyInfoIdSource = existingCopies[this.AsFacultyInfoIdSource] as AsFacultyInfo;
			else
				copy.AsFacultyInfoIdSource = MakeCopyOf(this.AsFacultyInfoIdSource, existingCopies) as AsFacultyInfo;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed EdAcadYearFaculty Entity 
		///</summary>
		public virtual EdAcadYearFaculty Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed EdAcadYearFaculty Entity which is a deep copy of the current entity.
		///</summary>
		public virtual EdAcadYearFaculty DeepCopy()
		{
			return EntityHelper.Clone<EdAcadYearFaculty>(this as EdAcadYearFaculty);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as EdAcadYearFacultyEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new EdAcadYearFacultyEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as EdAcadYearFacultyEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(EdAcadYearFacultyColumn column)
		{
			switch(column)
			{
					case EdAcadYearFacultyColumn.EdAcadYearFacultyId:
					return entityData.EdAcadYearFacultyId != _originalData.EdAcadYearFacultyId;
					case EdAcadYearFacultyColumn.AsFacultyInfoId:
					return entityData.AsFacultyInfoId != _originalData.AsFacultyInfoId;
					case EdAcadYearFacultyColumn.EdAcadYearId:
					return entityData.EdAcadYearId != _originalData.EdAcadYearId;
					case EdAcadYearFacultyColumn.StartDate:
					return entityData.StartDate != _originalData.StartDate;
					case EdAcadYearFacultyColumn.EndDate:
					return entityData.EndDate != _originalData.EndDate;
					case EdAcadYearFacultyColumn.CurrentYear:
					return entityData.CurrentYear != _originalData.CurrentYear;
					case EdAcadYearFacultyColumn.IsClosed:
					return entityData.IsClosed != _originalData.IsClosed;
					case EdAcadYearFacultyColumn.AsCodeDegreeClassId:
					return entityData.AsCodeDegreeClassId != _originalData.AsCodeDegreeClassId;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< EdAcadYearFacultyColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.EdAcadYearFacultyId != _originalData.EdAcadYearFacultyId;
			result = result || entityData.AsFacultyInfoId != _originalData.AsFacultyInfoId;
			result = result || entityData.EdAcadYearId != _originalData.EdAcadYearId;
			result = result || entityData.StartDate != _originalData.StartDate;
			result = result || entityData.EndDate != _originalData.EndDate;
			result = result || entityData.CurrentYear != _originalData.CurrentYear;
			result = result || entityData.IsClosed != _originalData.IsClosed;
			result = result || entityData.AsCodeDegreeClassId != _originalData.AsCodeDegreeClassId;
			return result;
		}	
		
		///<summary>
		///  Returns a EdAcadYearFaculty Entity with the original data.
		///</summary>
		public EdAcadYearFaculty GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateEdAcadYearFaculty(
				_originalData.EdAcadYearFacultyId,
				_originalData.AsFacultyInfoId,
				_originalData.EdAcadYearId,
				_originalData.StartDate,
				_originalData.EndDate,
				_originalData.CurrentYear,
				_originalData.IsClosed,
				_originalData.AsCodeDegreeClassId
				);
				
			return (EdAcadYearFaculty)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="EdAcadYearFacultyBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is EdAcadYearFacultyBase)
				return ValueEquals(this, (EdAcadYearFacultyBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="EdAcadYearFacultyBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.EdAcadYearFacultyId.GetHashCode() ^ 
					((this.AsFacultyInfoId == null) ? string.Empty : this.AsFacultyInfoId.ToString()).GetHashCode() ^ 
					this.EdAcadYearId.GetHashCode() ^ 
					this.StartDate.GetHashCode() ^ 
					this.EndDate.GetHashCode() ^ 
					((this.CurrentYear == null) ? string.Empty : this.CurrentYear.ToString()).GetHashCode() ^ 
					((this.IsClosed == null) ? string.Empty : this.IsClosed.ToString()).GetHashCode() ^ 
					((this.AsCodeDegreeClassId == null) ? string.Empty : this.AsCodeDegreeClassId.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="EdAcadYearFacultyBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(EdAcadYearFacultyBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="EdAcadYearFacultyBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="EdAcadYearFacultyBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="EdAcadYearFacultyBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(EdAcadYearFacultyBase Object1, EdAcadYearFacultyBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.EdAcadYearFacultyId != Object2.EdAcadYearFacultyId)
				equal = false;
			if ( Object1.AsFacultyInfoId != null && Object2.AsFacultyInfoId != null )
			{
				if (Object1.AsFacultyInfoId != Object2.AsFacultyInfoId)
					equal = false;
			}
			else if (Object1.AsFacultyInfoId == null ^ Object2.AsFacultyInfoId == null )
			{
				equal = false;
			}
			if (Object1.EdAcadYearId != Object2.EdAcadYearId)
				equal = false;
			if (Object1.StartDate != Object2.StartDate)
				equal = false;
			if (Object1.EndDate != Object2.EndDate)
				equal = false;
			if ( Object1.CurrentYear != null && Object2.CurrentYear != null )
			{
				if (Object1.CurrentYear != Object2.CurrentYear)
					equal = false;
			}
			else if (Object1.CurrentYear == null ^ Object2.CurrentYear == null )
			{
				equal = false;
			}
			if ( Object1.IsClosed != null && Object2.IsClosed != null )
			{
				if (Object1.IsClosed != Object2.IsClosed)
					equal = false;
			}
			else if (Object1.IsClosed == null ^ Object2.IsClosed == null )
			{
				equal = false;
			}
			if ( Object1.AsCodeDegreeClassId != null && Object2.AsCodeDegreeClassId != null )
			{
				if (Object1.AsCodeDegreeClassId != Object2.AsCodeDegreeClassId)
					equal = false;
			}
			else if (Object1.AsCodeDegreeClassId == null ^ Object2.AsCodeDegreeClassId == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((EdAcadYearFacultyBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static EdAcadYearFacultyComparer GetComparer()
        {
            return new EdAcadYearFacultyComparer();
        }
        */

        // Comparer delegates back to EdAcadYearFaculty
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(EdAcadYearFaculty rhs, EdAcadYearFacultyColumn which)
        {
            switch (which)
            {
            	
            	
            	case EdAcadYearFacultyColumn.EdAcadYearFacultyId:
            		return this.EdAcadYearFacultyId.CompareTo(rhs.EdAcadYearFacultyId);
            		
            		                 
            	
            	
            	case EdAcadYearFacultyColumn.AsFacultyInfoId:
            		return this.AsFacultyInfoId.Value.CompareTo(rhs.AsFacultyInfoId.Value);
            		
            		                 
            	
            	
            	case EdAcadYearFacultyColumn.EdAcadYearId:
            		return this.EdAcadYearId.CompareTo(rhs.EdAcadYearId);
            		
            		                 
            	
            	
            	case EdAcadYearFacultyColumn.StartDate:
            		return this.StartDate.CompareTo(rhs.StartDate);
            		
            		                 
            	
            	
            	case EdAcadYearFacultyColumn.EndDate:
            		return this.EndDate.CompareTo(rhs.EndDate);
            		
            		                 
            	
            	
            	case EdAcadYearFacultyColumn.CurrentYear:
            		return this.CurrentYear.Value.CompareTo(rhs.CurrentYear.Value);
            		
            		                 
            	
            	
            	case EdAcadYearFacultyColumn.IsClosed:
            		return this.IsClosed.Value.CompareTo(rhs.IsClosed.Value);
            		
            		                 
            	
            	
            	case EdAcadYearFacultyColumn.AsCodeDegreeClassId:
            		return this.AsCodeDegreeClassId.Value.CompareTo(rhs.AsCodeDegreeClassId.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<EdAcadYearFacultyKey> Members
		
		// member variable for the EntityId property
		private EdAcadYearFacultyKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual EdAcadYearFacultyKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new EdAcadYearFacultyKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("EdAcadYearFaculty")
					.Append("|").Append( this.EdAcadYearFacultyId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{9}{8}- EdAcadYearFacultyId: {0}{8}- AsFacultyInfoId: {1}{8}- EdAcadYearId: {2}{8}- StartDate: {3}{8}- EndDate: {4}{8}- CurrentYear: {5}{8}- IsClosed: {6}{8}- AsCodeDegreeClassId: {7}{8}{10}", 
				this.EdAcadYearFacultyId,
				(this.AsFacultyInfoId == null) ? string.Empty : this.AsFacultyInfoId.ToString(),
				this.EdAcadYearId,
				this.StartDate,
				this.EndDate,
				(this.CurrentYear == null) ? string.Empty : this.CurrentYear.ToString(),
				(this.IsClosed == null) ? string.Empty : this.IsClosed.ToString(),
				(this.AsCodeDegreeClassId == null) ? string.Empty : this.AsCodeDegreeClassId.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'ED_ACAD_YEAR_FACULTY' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class EdAcadYearFacultyEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// ED_ACAD_YEAR_FACULTY_ID : XXX
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ED_ACAD_YEAR_FACULTY"</remarks>
		public System.Decimal EdAcadYearFacultyId;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Decimal OriginalEdAcadYearFacultyId;
		
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// AS_FACULTY_INFO_ID : 
		/// </summary>
		public System.Decimal?		  AsFacultyInfoId = null;
		
		/// <summary>
		/// ED_ACAD_YEAR_ID : 
		/// </summary>
		public System.Decimal		  EdAcadYearId = 0.0m;
		
		/// <summary>
		/// START_DATE : 
		/// </summary>
		public System.DateTime		  StartDate = DateTime.MinValue;
		
		/// <summary>
		/// END_DATE : 
		/// </summary>
		public System.DateTime		  EndDate = DateTime.MinValue;
		
		/// <summary>
		/// CURRENT_YEAR : 
		/// </summary>
		public System.Decimal?		  CurrentYear = null;
		
		/// <summary>
		/// IS_CLOSED : 
		/// </summary>
		public System.Decimal?		  IsClosed = null;
		
		/// <summary>
		/// AS_CODE_DEGREE_CLASS_ID : 
		/// </summary>
		public System.Decimal?		  AsCodeDegreeClassId = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private EdAcadYear _edAcadYearIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="EdAcadYear"/>.
		/// </summary>
		/// <value>The source EdAcadYear for EdAcadYearId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual EdAcadYear EdAcadYearIdSource
      	{
            get { return this._edAcadYearIdSource; }
            set { this._edAcadYearIdSource = value; }
      	}
		private AsCodeDegreeClass _asCodeDegreeClassIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="AsCodeDegreeClass"/>.
		/// </summary>
		/// <value>The source AsCodeDegreeClass for AsCodeDegreeClassId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual AsCodeDegreeClass AsCodeDegreeClassIdSource
      	{
            get { return this._asCodeDegreeClassIdSource; }
            set { this._asCodeDegreeClassIdSource = value; }
      	}
		private AsFacultyInfo _asFacultyInfoIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="AsFacultyInfo"/>.
		/// </summary>
		/// <value>The source AsFacultyInfo for AsFacultyInfoId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual AsFacultyInfo AsFacultyInfoIdSource
      	{
            get { return this._asFacultyInfoIdSource; }
            set { this._asFacultyInfoIdSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			EdAcadYearFacultyEntityData _tmp = new EdAcadYearFacultyEntityData();
						
			_tmp.EdAcadYearFacultyId = this.EdAcadYearFacultyId;
			_tmp.OriginalEdAcadYearFacultyId = this.OriginalEdAcadYearFacultyId;
			
			_tmp.AsFacultyInfoId = this.AsFacultyInfoId;
			_tmp.EdAcadYearId = this.EdAcadYearId;
			_tmp.StartDate = this.StartDate;
			_tmp.EndDate = this.EndDate;
			_tmp.CurrentYear = this.CurrentYear;
			_tmp.IsClosed = this.IsClosed;
			_tmp.AsCodeDegreeClassId = this.AsCodeDegreeClassId;
			
			#region Source Parent Composite Entities
			if (this.EdAcadYearIdSource != null)
				_tmp.EdAcadYearIdSource = MakeCopyOf(this.EdAcadYearIdSource) as EdAcadYear;
			if (this.AsCodeDegreeClassIdSource != null)
				_tmp.AsCodeDegreeClassIdSource = MakeCopyOf(this.AsCodeDegreeClassIdSource) as AsCodeDegreeClass;
			if (this.AsFacultyInfoIdSource != null)
				_tmp.AsFacultyInfoIdSource = MakeCopyOf(this.AsFacultyInfoIdSource) as AsFacultyInfo;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			EdAcadYearFacultyEntityData _tmp = new EdAcadYearFacultyEntityData();
						
			_tmp.EdAcadYearFacultyId = this.EdAcadYearFacultyId;
			_tmp.OriginalEdAcadYearFacultyId = this.OriginalEdAcadYearFacultyId;
			
			_tmp.AsFacultyInfoId = this.AsFacultyInfoId;
			_tmp.EdAcadYearId = this.EdAcadYearId;
			_tmp.StartDate = this.StartDate;
			_tmp.EndDate = this.EndDate;
			_tmp.CurrentYear = this.CurrentYear;
			_tmp.IsClosed = this.IsClosed;
			_tmp.AsCodeDegreeClassId = this.AsCodeDegreeClassId;
			
			#region Source Parent Composite Entities
			if (this.EdAcadYearIdSource != null && existingCopies.Contains(this.EdAcadYearIdSource))
				_tmp.EdAcadYearIdSource = existingCopies[this.EdAcadYearIdSource] as EdAcadYear;
			else
				_tmp.EdAcadYearIdSource = MakeCopyOf(this.EdAcadYearIdSource, existingCopies) as EdAcadYear;
			if (this.AsCodeDegreeClassIdSource != null && existingCopies.Contains(this.AsCodeDegreeClassIdSource))
				_tmp.AsCodeDegreeClassIdSource = existingCopies[this.AsCodeDegreeClassIdSource] as AsCodeDegreeClass;
			else
				_tmp.AsCodeDegreeClassIdSource = MakeCopyOf(this.AsCodeDegreeClassIdSource, existingCopies) as AsCodeDegreeClass;
			if (this.AsFacultyInfoIdSource != null && existingCopies.Contains(this.AsFacultyInfoIdSource))
				_tmp.AsFacultyInfoIdSource = existingCopies[this.AsFacultyInfoIdSource] as AsFacultyInfo;
			else
				_tmp.AsFacultyInfoIdSource = MakeCopyOf(this.AsFacultyInfoIdSource, existingCopies) as AsFacultyInfo;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="EdAcadYearFacultyColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(EdAcadYearFacultyColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="EdAcadYearFacultyColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(EdAcadYearFacultyColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="EdAcadYearFacultyColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(EdAcadYearFacultyColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				EdAcadYearFacultyEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new EdAcadYearFacultyEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="EdAcadYearFacultyColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(EdAcadYearFacultyColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				EdAcadYearFacultyEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new EdAcadYearFacultyEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region EdAcadYearFacultyEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="EdAcadYearFaculty"/> object.
	/// </remarks>
	public class EdAcadYearFacultyEventArgs : System.EventArgs
	{
		private EdAcadYearFacultyColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the EdAcadYearFacultyEventArgs class.
		///</summary>
		public EdAcadYearFacultyEventArgs(EdAcadYearFacultyColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the EdAcadYearFacultyEventArgs class.
		///</summary>
		public EdAcadYearFacultyEventArgs(EdAcadYearFacultyColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The EdAcadYearFacultyColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="EdAcadYearFacultyColumn" />
		public EdAcadYearFacultyColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all EdAcadYearFaculty related events.
	///</summary>
	public delegate void EdAcadYearFacultyEventHandler(object sender, EdAcadYearFacultyEventArgs e);
	
	#region EdAcadYearFacultyComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class EdAcadYearFacultyComparer : System.Collections.Generic.IComparer<EdAcadYearFaculty>
	{
		EdAcadYearFacultyColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:EdAcadYearFacultyComparer"/> class.
        /// </summary>
		public EdAcadYearFacultyComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:EdAcadYearFacultyComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public EdAcadYearFacultyComparer(EdAcadYearFacultyColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="EdAcadYearFaculty"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="EdAcadYearFaculty"/> to compare.</param>
        /// <param name="b">The second <c>EdAcadYearFaculty</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(EdAcadYearFaculty a, EdAcadYearFaculty b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(EdAcadYearFaculty entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(EdAcadYearFaculty a, EdAcadYearFaculty b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public EdAcadYearFacultyColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region EdAcadYearFacultyKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="EdAcadYearFaculty"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class EdAcadYearFacultyKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the EdAcadYearFacultyKey class.
		/// </summary>
		public EdAcadYearFacultyKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the EdAcadYearFacultyKey class.
		/// </summary>
		public EdAcadYearFacultyKey(EdAcadYearFacultyBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.EdAcadYearFacultyId = entity.EdAcadYearFacultyId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the EdAcadYearFacultyKey class.
		/// </summary>
		public EdAcadYearFacultyKey(System.Decimal _edAcadYearFacultyId)
		{
			#region Init Properties

			this.EdAcadYearFacultyId = _edAcadYearFacultyId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private EdAcadYearFacultyBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public EdAcadYearFacultyBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the EdAcadYearFacultyId property
		private System.Decimal _edAcadYearFacultyId;
		
		/// <summary>
		/// Gets or sets the EdAcadYearFacultyId property.
		/// </summary>
		public System.Decimal EdAcadYearFacultyId
		{
			get { return _edAcadYearFacultyId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.EdAcadYearFacultyId = value;
				
				_edAcadYearFacultyId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				EdAcadYearFacultyId = ( values["EdAcadYearFacultyId"] != null ) ? (System.Decimal) EntityUtil.ChangeType(values["EdAcadYearFacultyId"], typeof(System.Decimal)) : 0.0m;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("EdAcadYearFacultyId", EdAcadYearFacultyId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("EdAcadYearFacultyId: {0}{1}",
								EdAcadYearFacultyId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region EdAcadYearFacultyColumn Enum
	
	/// <summary>
	/// Enumerate the EdAcadYearFaculty columns.
	/// </summary>
	[Serializable]
	public enum EdAcadYearFacultyColumn : int
	{
		/// <summary>
		/// EdAcadYearFacultyId : XXX
		/// </summary>
		[EnumTextValue("ED_ACAD_YEAR_FACULTY_ID")]
		[ColumnEnum("ED_ACAD_YEAR_FACULTY_ID", typeof(System.Decimal), System.Data.DbType.Decimal, true, false, false)]
		EdAcadYearFacultyId = 1,
		/// <summary>
		/// AsFacultyInfoId : 
		/// </summary>
		[EnumTextValue("AS_FACULTY_INFO_ID")]
		[ColumnEnum("AS_FACULTY_INFO_ID", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		AsFacultyInfoId = 2,
		/// <summary>
		/// EdAcadYearId : 
		/// </summary>
		[EnumTextValue("ED_ACAD_YEAR_ID")]
		[ColumnEnum("ED_ACAD_YEAR_ID", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, false)]
		EdAcadYearId = 3,
		/// <summary>
		/// StartDate : 
		/// </summary>
		[EnumTextValue("START_DATE")]
		[ColumnEnum("START_DATE", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		StartDate = 4,
		/// <summary>
		/// EndDate : 
		/// </summary>
		[EnumTextValue("END_DATE")]
		[ColumnEnum("END_DATE", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		EndDate = 5,
		/// <summary>
		/// CurrentYear : 
		/// </summary>
		[EnumTextValue("CURRENT_YEAR")]
		[ColumnEnum("CURRENT_YEAR", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		CurrentYear = 6,
		/// <summary>
		/// IsClosed : 
		/// </summary>
		[EnumTextValue("IS_CLOSED")]
		[ColumnEnum("IS_CLOSED", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		IsClosed = 7,
		/// <summary>
		/// AsCodeDegreeClassId : 
		/// </summary>
		[EnumTextValue("AS_CODE_DEGREE_CLASS_ID")]
		[ColumnEnum("AS_CODE_DEGREE_CLASS_ID", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		AsCodeDegreeClassId = 8
	}//End enum

	#endregion EdAcadYearFacultyColumn Enum

} // end namespace
