
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file EdProjStud.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using UMIS_VER2.BusinessLyer.Validation;
#endregion

namespace UMIS_VER2.BusinessLyer
{
	///<summary>
	/// An object representation of the 'ED_PROJ_STUD' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class EdProjStudBase : EntityBase, IEdProjStud, IEntityId<EdProjStudKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private EdProjStudEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private EdProjStudEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private EdProjStudEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<EdProjStud> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event EdProjStudEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event EdProjStudEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="EdProjStudBase"/> instance.
		///</summary>
		public EdProjStudBase()
		{
			this.entityData = new EdProjStudEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="EdProjStudBase"/> instance.
		///</summary>
		///<param name="_edProjStudId"></param>
		///<param name="_edProjectId"></param>
		///<param name="_edStudId"></param>
		///<param name="_edCourseId"></param>
		public EdProjStudBase(System.Decimal _edProjStudId, System.Decimal _edProjectId, 
			System.Decimal _edStudId, System.Decimal? _edCourseId)
		{
			this.entityData = new EdProjStudEntityData();
			this.backupData = null;

			this.EdProjStudId = _edProjStudId;
			this.EdProjectId = _edProjectId;
			this.EdStudId = _edStudId;
			this.EdCourseId = _edCourseId;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="EdProjStud"/> instance.
		///</summary>
		///<param name="_edProjStudId"></param>
		///<param name="_edProjectId"></param>
		///<param name="_edStudId"></param>
		///<param name="_edCourseId"></param>
		public static EdProjStud CreateEdProjStud(System.Decimal _edProjStudId, System.Decimal _edProjectId, 
			System.Decimal _edStudId, System.Decimal? _edCourseId)
		{
			EdProjStud newEdProjStud = new EdProjStud();
			newEdProjStud.EdProjStudId = _edProjStudId;
			newEdProjStud.EdProjectId = _edProjectId;
			newEdProjStud.EdStudId = _edStudId;
			newEdProjStud.EdCourseId = _edCourseId;
			return newEdProjStud;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the EdProjStudId property. 
		///		
		/// </summary>
		/// <value>This type is numeric.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Decimal EdProjStudId
		{
			get
			{
				return this.entityData.EdProjStudId; 
			}
			
			set
			{
				if (this.entityData.EdProjStudId == value)
					return;
					
				OnColumnChanging(EdProjStudColumn.EdProjStudId, this.entityData.EdProjStudId);
				this.entityData.EdProjStudId = value;
				this.EntityId.EdProjStudId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EdProjStudColumn.EdProjStudId, this.entityData.EdProjStudId);
				OnPropertyChanged("EdProjStudId");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the ED_PROJ_STUD_ID property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the ED_PROJ_STUD_ID property.</remarks>
		/// <value>This type is numeric</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Decimal OriginalEdProjStudId
		{
			get { return this.entityData.OriginalEdProjStudId; }
			set { this.entityData.OriginalEdProjStudId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the EdProjectId property. 
		///		
		/// </summary>
		/// <value>This type is numeric.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Decimal EdProjectId
		{
			get
			{
				return this.entityData.EdProjectId; 
			}
			
			set
			{
				if (this.entityData.EdProjectId == value)
					return;
					
				OnColumnChanging(EdProjStudColumn.EdProjectId, this.entityData.EdProjectId);
				this.entityData.EdProjectId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EdProjStudColumn.EdProjectId, this.entityData.EdProjectId);
				OnPropertyChanged("EdProjectId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the EdStudId property. 
		///		
		/// </summary>
		/// <value>This type is numeric.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Decimal EdStudId
		{
			get
			{
				return this.entityData.EdStudId; 
			}
			
			set
			{
				if (this.entityData.EdStudId == value)
					return;
					
				OnColumnChanging(EdProjStudColumn.EdStudId, this.entityData.EdStudId);
				this.entityData.EdStudId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EdProjStudColumn.EdStudId, this.entityData.EdStudId);
				OnPropertyChanged("EdStudId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the EdCourseId property. 
		///		
		/// </summary>
		/// <value>This type is numeric.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0m. It is up to the developer
		/// to check the value of IsEdCourseIdNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Decimal? EdCourseId
		{
			get
			{
				return this.entityData.EdCourseId; 
			}
			
			set
			{
				if (this.entityData.EdCourseId == value)
					return;
					
				OnColumnChanging(EdProjStudColumn.EdCourseId, this.entityData.EdCourseId);
				this.entityData.EdCourseId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(EdProjStudColumn.EdCourseId, this.entityData.EdCourseId);
				OnPropertyChanged("EdCourseId");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="EdCourse"/>.
		/// </summary>
		/// <value>The source EdCourse for EdCourseId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual EdCourse EdCourseIdSource
      	{
            get { return entityData.EdCourseIdSource; }
            set { entityData.EdCourseIdSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="EdProject"/>.
		/// </summary>
		/// <value>The source EdProject for EdProjectId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual EdProject EdProjectIdSource
      	{
            get { return entityData.EdProjectIdSource; }
            set { entityData.EdProjectIdSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="EdStud"/>.
		/// </summary>
		/// <value>The source EdStud for EdStudId.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual EdStud EdStudIdSource
      	{
            get { return entityData.EdStudIdSource; }
            set { entityData.EdStudIdSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "ED_PROJ_STUD"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ED_PROJ_STUD_ID", "ED_PROJECT_ID", "ED_STUD_ID", "ED_COURSE_ID"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as EdProjStudEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (EdProjStud) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<EdProjStud>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as EdProjStud);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed EdProjStud Entity 
		///</summary>
		protected virtual EdProjStud Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			EdProjStud copy = new EdProjStud();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.EdProjStudId = this.EdProjStudId;
					copy.OriginalEdProjStudId = this.OriginalEdProjStudId;
				copy.EdProjectId = this.EdProjectId;
				copy.EdStudId = this.EdStudId;
				copy.EdCourseId = this.EdCourseId;
			
			if (this.EdCourseIdSource != null && existingCopies.Contains(this.EdCourseIdSource))
				copy.EdCourseIdSource = existingCopies[this.EdCourseIdSource] as EdCourse;
			else
				copy.EdCourseIdSource = MakeCopyOf(this.EdCourseIdSource, existingCopies) as EdCourse;
			if (this.EdProjectIdSource != null && existingCopies.Contains(this.EdProjectIdSource))
				copy.EdProjectIdSource = existingCopies[this.EdProjectIdSource] as EdProject;
			else
				copy.EdProjectIdSource = MakeCopyOf(this.EdProjectIdSource, existingCopies) as EdProject;
			if (this.EdStudIdSource != null && existingCopies.Contains(this.EdStudIdSource))
				copy.EdStudIdSource = existingCopies[this.EdStudIdSource] as EdStud;
			else
				copy.EdStudIdSource = MakeCopyOf(this.EdStudIdSource, existingCopies) as EdStud;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed EdProjStud Entity 
		///</summary>
		public virtual EdProjStud Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed EdProjStud Entity which is a deep copy of the current entity.
		///</summary>
		public virtual EdProjStud DeepCopy()
		{
			return EntityHelper.Clone<EdProjStud>(this as EdProjStud);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as EdProjStudEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new EdProjStudEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as EdProjStudEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(EdProjStudColumn column)
		{
			switch(column)
			{
					case EdProjStudColumn.EdProjStudId:
					return entityData.EdProjStudId != _originalData.EdProjStudId;
					case EdProjStudColumn.EdProjectId:
					return entityData.EdProjectId != _originalData.EdProjectId;
					case EdProjStudColumn.EdStudId:
					return entityData.EdStudId != _originalData.EdStudId;
					case EdProjStudColumn.EdCourseId:
					return entityData.EdCourseId != _originalData.EdCourseId;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< EdProjStudColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.EdProjStudId != _originalData.EdProjStudId;
			result = result || entityData.EdProjectId != _originalData.EdProjectId;
			result = result || entityData.EdStudId != _originalData.EdStudId;
			result = result || entityData.EdCourseId != _originalData.EdCourseId;
			return result;
		}	
		
		///<summary>
		///  Returns a EdProjStud Entity with the original data.
		///</summary>
		public EdProjStud GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateEdProjStud(
				_originalData.EdProjStudId,
				_originalData.EdProjectId,
				_originalData.EdStudId,
				_originalData.EdCourseId
				);
				
			return (EdProjStud)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="EdProjStudBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is EdProjStudBase)
				return ValueEquals(this, (EdProjStudBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="EdProjStudBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.EdProjStudId.GetHashCode() ^ 
					this.EdProjectId.GetHashCode() ^ 
					this.EdStudId.GetHashCode() ^ 
					((this.EdCourseId == null) ? string.Empty : this.EdCourseId.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="EdProjStudBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(EdProjStudBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="EdProjStudBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="EdProjStudBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="EdProjStudBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(EdProjStudBase Object1, EdProjStudBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.EdProjStudId != Object2.EdProjStudId)
				equal = false;
			if (Object1.EdProjectId != Object2.EdProjectId)
				equal = false;
			if (Object1.EdStudId != Object2.EdStudId)
				equal = false;
			if ( Object1.EdCourseId != null && Object2.EdCourseId != null )
			{
				if (Object1.EdCourseId != Object2.EdCourseId)
					equal = false;
			}
			else if (Object1.EdCourseId == null ^ Object2.EdCourseId == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((EdProjStudBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static EdProjStudComparer GetComparer()
        {
            return new EdProjStudComparer();
        }
        */

        // Comparer delegates back to EdProjStud
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(EdProjStud rhs, EdProjStudColumn which)
        {
            switch (which)
            {
            	
            	
            	case EdProjStudColumn.EdProjStudId:
            		return this.EdProjStudId.CompareTo(rhs.EdProjStudId);
            		
            		                 
            	
            	
            	case EdProjStudColumn.EdProjectId:
            		return this.EdProjectId.CompareTo(rhs.EdProjectId);
            		
            		                 
            	
            	
            	case EdProjStudColumn.EdStudId:
            		return this.EdStudId.CompareTo(rhs.EdStudId);
            		
            		                 
            	
            	
            	case EdProjStudColumn.EdCourseId:
            		return this.EdCourseId.Value.CompareTo(rhs.EdCourseId.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<EdProjStudKey> Members
		
		// member variable for the EntityId property
		private EdProjStudKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual EdProjStudKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new EdProjStudKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("EdProjStud")
					.Append("|").Append( this.EdProjStudId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{5}{4}- EdProjStudId: {0}{4}- EdProjectId: {1}{4}- EdStudId: {2}{4}- EdCourseId: {3}{4}{6}", 
				this.EdProjStudId,
				this.EdProjectId,
				this.EdStudId,
				(this.EdCourseId == null) ? string.Empty : this.EdCourseId.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'ED_PROJ_STUD' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class EdProjStudEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// ED_PROJ_STUD_ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ED_PROJ_STUD"</remarks>
		public System.Decimal EdProjStudId;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Decimal OriginalEdProjStudId;
		
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// ED_PROJECT_ID : 
		/// </summary>
		public System.Decimal		  EdProjectId = 0.0m;
		
		/// <summary>
		/// ED_STUD_ID : 
		/// </summary>
		public System.Decimal		  EdStudId = 0.0m;
		
		/// <summary>
		/// ED_COURSE_ID : 
		/// </summary>
		public System.Decimal?		  EdCourseId = null;
		#endregion
			
		#region Source Foreign Key Property
				
		private EdCourse _edCourseIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="EdCourse"/>.
		/// </summary>
		/// <value>The source EdCourse for EdCourseId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual EdCourse EdCourseIdSource
      	{
            get { return this._edCourseIdSource; }
            set { this._edCourseIdSource = value; }
      	}
		private EdProject _edProjectIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="EdProject"/>.
		/// </summary>
		/// <value>The source EdProject for EdProjectId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual EdProject EdProjectIdSource
      	{
            get { return this._edProjectIdSource; }
            set { this._edProjectIdSource = value; }
      	}
		private EdStud _edStudIdSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="EdStud"/>.
		/// </summary>
		/// <value>The source EdStud for EdStudId.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual EdStud EdStudIdSource
      	{
            get { return this._edStudIdSource; }
            set { this._edStudIdSource = value; }
      	}
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			EdProjStudEntityData _tmp = new EdProjStudEntityData();
						
			_tmp.EdProjStudId = this.EdProjStudId;
			_tmp.OriginalEdProjStudId = this.OriginalEdProjStudId;
			
			_tmp.EdProjectId = this.EdProjectId;
			_tmp.EdStudId = this.EdStudId;
			_tmp.EdCourseId = this.EdCourseId;
			
			#region Source Parent Composite Entities
			if (this.EdCourseIdSource != null)
				_tmp.EdCourseIdSource = MakeCopyOf(this.EdCourseIdSource) as EdCourse;
			if (this.EdProjectIdSource != null)
				_tmp.EdProjectIdSource = MakeCopyOf(this.EdProjectIdSource) as EdProject;
			if (this.EdStudIdSource != null)
				_tmp.EdStudIdSource = MakeCopyOf(this.EdStudIdSource) as EdStud;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			EdProjStudEntityData _tmp = new EdProjStudEntityData();
						
			_tmp.EdProjStudId = this.EdProjStudId;
			_tmp.OriginalEdProjStudId = this.OriginalEdProjStudId;
			
			_tmp.EdProjectId = this.EdProjectId;
			_tmp.EdStudId = this.EdStudId;
			_tmp.EdCourseId = this.EdCourseId;
			
			#region Source Parent Composite Entities
			if (this.EdCourseIdSource != null && existingCopies.Contains(this.EdCourseIdSource))
				_tmp.EdCourseIdSource = existingCopies[this.EdCourseIdSource] as EdCourse;
			else
				_tmp.EdCourseIdSource = MakeCopyOf(this.EdCourseIdSource, existingCopies) as EdCourse;
			if (this.EdProjectIdSource != null && existingCopies.Contains(this.EdProjectIdSource))
				_tmp.EdProjectIdSource = existingCopies[this.EdProjectIdSource] as EdProject;
			else
				_tmp.EdProjectIdSource = MakeCopyOf(this.EdProjectIdSource, existingCopies) as EdProject;
			if (this.EdStudIdSource != null && existingCopies.Contains(this.EdStudIdSource))
				_tmp.EdStudIdSource = existingCopies[this.EdStudIdSource] as EdStud;
			else
				_tmp.EdStudIdSource = MakeCopyOf(this.EdStudIdSource, existingCopies) as EdStud;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="EdProjStudColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(EdProjStudColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="EdProjStudColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(EdProjStudColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="EdProjStudColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(EdProjStudColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				EdProjStudEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new EdProjStudEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="EdProjStudColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(EdProjStudColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				EdProjStudEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new EdProjStudEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region EdProjStudEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="EdProjStud"/> object.
	/// </remarks>
	public class EdProjStudEventArgs : System.EventArgs
	{
		private EdProjStudColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the EdProjStudEventArgs class.
		///</summary>
		public EdProjStudEventArgs(EdProjStudColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the EdProjStudEventArgs class.
		///</summary>
		public EdProjStudEventArgs(EdProjStudColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The EdProjStudColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="EdProjStudColumn" />
		public EdProjStudColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all EdProjStud related events.
	///</summary>
	public delegate void EdProjStudEventHandler(object sender, EdProjStudEventArgs e);
	
	#region EdProjStudComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class EdProjStudComparer : System.Collections.Generic.IComparer<EdProjStud>
	{
		EdProjStudColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:EdProjStudComparer"/> class.
        /// </summary>
		public EdProjStudComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:EdProjStudComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public EdProjStudComparer(EdProjStudColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="EdProjStud"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="EdProjStud"/> to compare.</param>
        /// <param name="b">The second <c>EdProjStud</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(EdProjStud a, EdProjStud b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(EdProjStud entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(EdProjStud a, EdProjStud b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public EdProjStudColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region EdProjStudKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="EdProjStud"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class EdProjStudKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the EdProjStudKey class.
		/// </summary>
		public EdProjStudKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the EdProjStudKey class.
		/// </summary>
		public EdProjStudKey(EdProjStudBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.EdProjStudId = entity.EdProjStudId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the EdProjStudKey class.
		/// </summary>
		public EdProjStudKey(System.Decimal _edProjStudId)
		{
			#region Init Properties

			this.EdProjStudId = _edProjStudId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private EdProjStudBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public EdProjStudBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the EdProjStudId property
		private System.Decimal _edProjStudId;
		
		/// <summary>
		/// Gets or sets the EdProjStudId property.
		/// </summary>
		public System.Decimal EdProjStudId
		{
			get { return _edProjStudId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.EdProjStudId = value;
				
				_edProjStudId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				EdProjStudId = ( values["EdProjStudId"] != null ) ? (System.Decimal) EntityUtil.ChangeType(values["EdProjStudId"], typeof(System.Decimal)) : 0.0m;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("EdProjStudId", EdProjStudId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("EdProjStudId: {0}{1}",
								EdProjStudId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region EdProjStudColumn Enum
	
	/// <summary>
	/// Enumerate the EdProjStud columns.
	/// </summary>
	[Serializable]
	public enum EdProjStudColumn : int
	{
		/// <summary>
		/// EdProjStudId : 
		/// </summary>
		[EnumTextValue("ED_PROJ_STUD_ID")]
		[ColumnEnum("ED_PROJ_STUD_ID", typeof(System.Decimal), System.Data.DbType.Decimal, true, false, false)]
		EdProjStudId = 1,
		/// <summary>
		/// EdProjectId : 
		/// </summary>
		[EnumTextValue("ED_PROJECT_ID")]
		[ColumnEnum("ED_PROJECT_ID", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, false)]
		EdProjectId = 2,
		/// <summary>
		/// EdStudId : 
		/// </summary>
		[EnumTextValue("ED_STUD_ID")]
		[ColumnEnum("ED_STUD_ID", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, false)]
		EdStudId = 3,
		/// <summary>
		/// EdCourseId : 
		/// </summary>
		[EnumTextValue("ED_COURSE_ID")]
		[ColumnEnum("ED_COURSE_ID", typeof(System.Decimal), System.Data.DbType.Decimal, false, false, true)]
		EdCourseId = 4
	}//End enum

	#endregion EdProjStudColumn Enum

} // end namespace
