using System;
using System.ComponentModel;

namespace UMIS_VER2.BusinessLyer
{
	/// <summary>
	///		The data structure representation of the 'ACCOM_AGENDA' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IAccomAgenda 
	{
		/// <summary>			
		/// ACCOM_AGENDA_ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ACCOM_AGENDA"</remarks>
		System.Int32 AccomAgendaId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Int32 OriginalAccomAgendaId { get; set; }
			
		
		
		/// <summary>
		/// ED_ACAD_YEAR_ID : 
		/// </summary>
		System.Decimal  EdAcadYearId  { get; set; }
		
		/// <summary>
		/// ED_CODE_SEMESTER_ID : مسلسل الفصل الدراسي
		/// </summary>
		System.Decimal  EdCodeSemesterId  { get; set; }
		
		/// <summary>
		/// ACCOM_CDE_ACTIVITY_ID : 
		/// </summary>
		System.Int32  AccomCdeActivityId  { get; set; }
		
		/// <summary>
		/// FROM_DATE : 
		/// </summary>
		System.DateTime?  FromDate  { get; set; }
		
		/// <summary>
		/// TO_DATE : 
		/// </summary>
		System.DateTime?  ToDate  { get; set; }
		
		/// <summary>
		/// SE_USER_ID : 
		/// </summary>
		System.Decimal?  SeUserId  { get; set; }
		
		/// <summary>
		/// LAST_DATE : 
		/// </summary>
		System.DateTime?  LastDate  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


