using System;
using System.ComponentModel;

namespace UMIS_VER2.BusinessLyer
{
	/// <summary>
	///		The data structure representation of the 'ADM_FEE_QUAL_CAT' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IAdmFeeQualCat 
	{
		/// <summary>			
		/// ADM_FEE_QUAL_CAT_ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ADM_FEE_QUAL_CAT"</remarks>
		System.Decimal AdmFeeQualCatId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Decimal OriginalAdmFeeQualCatId { get; set; }
			
		
		
		/// <summary>
		/// ADM_CDE_FEE_ID : 
		/// </summary>
		System.Decimal  AdmCdeFeeId  { get; set; }
		
		/// <summary>
		/// ED_CDE_QUAL_CAT_ID : 
		/// </summary>
		System.Decimal  EdCdeQualCatId  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


