using System;
using System.ComponentModel;

namespace UMIS_VER2.BusinessLyer
{
	/// <summary>
	///		The data structure representation of the 'ADM_TRANS_ACCEPTANCE_CATEGORY' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IAdmTransAcceptanceCategory 
	{
		/// <summary>			
		/// ADM_TRANS_ACCEPTANCE_CATEGORY_ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ADM_TRANS_ACCEPTANCE_CATEGORY"</remarks>
		System.Decimal AdmTransAcceptanceCategoryId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Decimal OriginalAdmTransAcceptanceCategoryId { get; set; }
			
		
		
		/// <summary>
		/// CATEGORY_NAME_EN : 
		/// </summary>
		System.String  CategoryNameEn  { get; set; }
		
		/// <summary>
		/// CATEGORY_NAME_AR : 
		/// </summary>
		System.String  CategoryNameAr  { get; set; }
		
		/// <summary>
		/// CATEGORY_TYPE : 
		/// </summary>
		System.Decimal  CategoryType  { get; set; }
		
		/// <summary>
		/// CATEGORY_VALUE : 
		/// </summary>
		System.Decimal  CategoryValue  { get; set; }
		
		/// <summary>
		/// ABBREVIATION_EN : 
		/// </summary>
		System.String  AbbreviationEn  { get; set; }
		
		/// <summary>
		/// ABBREVIATION_AR : 
		/// </summary>
		System.String  AbbreviationAr  { get; set; }
		
		/// <summary>
		/// REG_EXPIRATION : 
		/// </summary>
		System.String  RegExpiration  { get; set; }
		
		/// <summary>
		/// AS_CODE_DEGREE_CLASS_ID : 
		/// </summary>
		System.Decimal  AsCodeDegreeClassId  { get; set; }
		
		/// <summary>
		/// AS_CODE_DEGREE_ID : 
		/// </summary>
		System.Decimal  AsCodeDegreeId  { get; set; }
		
		/// <summary>
		/// ADM_CODE_TRANSFER_TYPE_ID : 
		/// </summary>
		System.Decimal  AdmCodeTransferTypeId  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _admTransferAcceptanceAdmTransAcceptanceCategoryId
		/// </summary>	
		TList<AdmTransferAcceptance> AdmTransferAcceptanceCollection {  get;  set;}	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _admIntTransferAcceptanceAdmTransAcceptanceCategoryId
		/// </summary>	
		TList<AdmIntTransferAcceptance> AdmIntTransferAcceptanceCollection {  get;  set;}	

		#endregion Data Properties

	}
}


