using System;
using System.ComponentModel;

namespace UMIS_VER2.BusinessLyer
{
	/// <summary>
	///		The data structure representation of the 'ED_INTTRANS_RULE' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IEdInttransRule 
	{
		/// <summary>			
		/// ED_INTTRANS_RULE_ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "ED_INTTRANS_RULE"</remarks>
		System.Decimal EdInttransRuleId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Decimal OriginalEdInttransRuleId { get; set; }
			
		
		
		/// <summary>
		/// ED_ACAD_YEAR_ID : 
		/// </summary>
		System.Decimal  EdAcadYearId  { get; set; }
		
		/// <summary>
		/// ED_CODE_SEMESTER_ID : 
		/// </summary>
		System.Decimal  EdCodeSemesterId  { get; set; }
		
		/// <summary>
		/// ENT_MAIN_ID : 
		/// </summary>
		System.Decimal  EntMainId  { get; set; }
		
		/// <summary>
		/// MIN_CGPA : 
		/// </summary>
		System.Decimal?  MinCgpa  { get; set; }
		
		/// <summary>
		/// MAX_STUD_NUM : 
		/// </summary>
		System.Decimal  MaxStudNum  { get; set; }
		
		/// <summary>
		/// IS_APPROVED : 
		/// </summary>
		System.Decimal  IsApproved  { get; set; }
		
		/// <summary>
		/// AS_FACULTY_INFO_ID : 
		/// </summary>
		System.Decimal  AsFacultyInfoId  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


