using System;
using System.ComponentModel;

namespace UMIS_VER2.BusinessLyer
{
	/// <summary>
	///		The data structure representation of the 'PG_CODE_CHANGE_TYPE' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IPgCodeChangeType 
	{
		/// <summary>			
		/// PG_CODE_CHANGE_TYPE_ID : مسلسل نوع التغيير
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "PG_CODE_CHANGE_TYPE"</remarks>
		System.Int32 PgCodeChangeTypeId { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Int32 OriginalPgCodeChangeTypeId { get; set; }
			
		
		
		/// <summary>
		/// CHANGE_TYPE_CODE : كود نوع التغيير
		/// </summary>
		System.String  ChangeTypeCode  { get; set; }
		
		/// <summary>
		/// CHANGE_TYPE_AR : وصف نوع التغيير
		/// </summary>
		System.String  ChangeTypeAr  { get; set; }
		
		/// <summary>
		/// CHANGE_TYPE_EN : وصف نوع التغيير
		/// </summary>
		System.String  ChangeTypeEn  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _pgThesisStudTopicPgCodeChangeTypeId
		/// </summary>	
		TList<PgThesisStudTopic> PgThesisStudTopicCollection {  get;  set;}	

		#endregion Data Properties

	}
}


